# Generated by Django 4.2.5 on 2024-05-10 22:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('sku', models.CharField(max_length=100)),
                ('marca', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=300)),
                ('precio', models.IntegerField()),
                ('fecha', models.DateField(auto_now_add=True)),
                ('stock', models.IntegerField()),
                ('valor', models.IntegerField()),
                ('imagen_url', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='TipoUsuario',
            fields=[
                ('id_tipo_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Ejemplo',
        ),
        migrations.RemoveField(
            model_name='usuariopersonalizado',
            name='telefono',
        ),
        migrations.AddField(
            model_name='usuariopersonalizado',
            name='id_tipo_usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.tipousuario'),
        ),
    ]
