# Generated by Django 4.2.5 on 2024-05-11 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_delete_tipoestado_alter_estado_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estado',
            name='id_estado',
            field=models.AutoField(choices=[(1, 'Aceptado'), (2, 'En proceso'), (3, 'Enviado'), (4, 'Finalizado'), (5, 'Reembolsado'), (6, 'Pendiente de pago')], primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='estado',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
    ]
