# Generated by Django 4.2.5 on 2024-05-12 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_estado_id_estado_alter_estado_nombre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuariopersonalizado',
            old_name='id_tipo_usuario',
            new_name='tipo_usuario',
        ),
    ]
