# Generated by Django 4.2.5 on 2024-05-12 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_rename_id_tipo_usuario_usuariopersonalizado_tipo_usuario'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='detallepedido',
            unique_together={('id_pedido', 'id_producto')},
        ),
    ]
