# Generated by Django 4.2.5 on 2024-05-12 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_detallepedido_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detallepedido',
            old_name='id_pedido',
            new_name='pedido',
        ),
        migrations.RenameField(
            model_name='detallepedido',
            old_name='id_producto',
            new_name='producto',
        ),
        migrations.RenameField(
            model_name='pago',
            old_name='id_estado_pago',
            new_name='estado_pago',
        ),
        migrations.RenameField(
            model_name='pago',
            old_name='id_metodo_pago',
            new_name='metodo_pago',
        ),
        migrations.RenameField(
            model_name='pago',
            old_name='id_pedido',
            new_name='pedido',
        ),
        migrations.RenameField(
            model_name='pedido',
            old_name='id_estado',
            new_name='estado',
        ),
        migrations.RenameField(
            model_name='pedido',
            old_name='id_usuario',
            new_name='usuario',
        ),
        migrations.RenameField(
            model_name='transaccion',
            old_name='id_cliente',
            new_name='cliente',
        ),
        migrations.RenameField(
            model_name='transaccion',
            old_name='id_pago',
            new_name='pago',
        ),
        migrations.RenameField(
            model_name='transaccion',
            old_name='id_pedido',
            new_name='pedido',
        ),
        migrations.AlterUniqueTogether(
            name='detallepedido',
            unique_together={('pedido', 'producto')},
        ),
    ]
