# Generated by Django 4.2.5 on 2024-05-12 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_pedido_iva_alter_pedido_subtotal_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuariopersonalizado',
            old_name='tipo_usuario',
            new_name='id_tipo_usuario',
        ),
    ]
