# Generated by Django 4.2.5 on 2024-05-12 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_rename_tipo_usuario_usuariopersonalizado_id_tipo_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='usuario',
            new_name='id_usuario',
        ),
    ]
