# Generated by Django 4.2.5 on 2024-05-12 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_rename_usuario_pedido_id_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='id_usuario',
            new_name='usuario',
        ),
    ]
