# Generated by Django 4.2.5 on 2024-05-13 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_pedido_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='metodopago',
            name='descripcion',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='metodopago',
            name='id_metodo_pago',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pago',
            name='fecha',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='fecha',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='id_transaccion',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
