# Generated by Django 4.2.5 on 2024-05-13 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_estadopago_id_estado_pago'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaccion',
            name='fecha',
        ),
    ]
